### ISSUE TITLE
Unable to send second email on the same email

### ISSUE THREAD

**Issue by Muneeb-Ahmed2002** [emailjs-com/emailjs-flutter#1] opened 2023-07-09 17:52 UTC
Whenever I try to send another email without killing the application it don't send another email meanwhile it shows some error message like this 
D/EGL_emulation(25261): app_time_stats: avg=14839.96ms min=3.09ms max=252025.66ms count=17
I/flutter (25261): ClientException: HTTP request failed. Client is already closed., uri=https://api.emailjs.com/api/v1.0/email/send

**Comment by xr0master** [comment] 2023-07-10 02:48
Hey, are you using our SDK?

**Comment by Muneeb-Ahmed2002** [comment] 2023-07-10 03:22
Yeah I am using the emailjs sdk meanwhile I found a way to send emails
again after sending one with the init method

**Comment by xr0master** [comment] 2023-07-10 03:30
Yes, this is indeed a bug, thanks.

**Comment by xr0master** [comment] 2023-07-10 03:59
@Muneeb-Ahmed2002 A new version 1.3.0 should be good now. Please try.

**Comment by puahhhh** [comment] 2023-08-01 07:54
I have 2 email, email A and email B

after upgrading to version 1.3.0, I'm able to send the mail content to multiple email on first try but when I send for the 2nd time to multiple email, only the first email (email A) is able to receive the mail content, but the other email (email B) doesn't receive the mail content. 

The EmailJSResponseStatus returns 200.

I've checked the email history in https://dashboard.emailjs.com/admin/history , both history has "sendTo" email A and email B

Please help out.

**Comment by xr0master** [comment] 2023-08-05 07:37
@puahhhh Please try to debug and find the issue. If it's into SDK, let us know.
However, since you see these entries in the Email History, it means that the problem is not on the EmailJS side.

**Comment by geniusvale** [comment] 2023-08-24 07:51
i have the same issue when trying to send another email after sending one.

I/flutter ( 7445): HTTP request failed. Client is already closed.

**Comment by xr0master** [comment] 2023-08-24 14:49
We will investigate it, thank you.

**Comment by xr0master** [comment] 2023-08-25 08:04
Unfortunately, we cannot reproduce this issue. Our example in the project works without errors.

What is the flutter version? Platform?
Can you share the code where you are calling the `EmailJS.send`.

**Comment by geniusvale** [comment] 2023-08-27 08:31
I use flutter 3 and android platform for debugging.

Here's the code :
`try {
        await emailJs.EmailJS.send(
          'someServiceCode',
          'someTemplateCode',
          templateParams(
            namaPembeli: userData.username!,
            namaPenjual: cartItems.products!.profiles!.username,
            emailPembeli: userData.email,
            emailPenjual: cartItems.products!.profiles!.email,
          ),
          const emailJs.Options(
            publicKey: 'somePublicKey',
            privateKey: 'somePrivateKey',
          ),
        );
        print('SUCCESS SEND EMAIL');
      } catch (e) {
        print(e.toString());
      }
      
      if (cartItems.products!.category == 'Produk Fisik') {
        try {
          await emailJs.EmailJS.send(
            'service_mzp1eji',
            'template_ajcpfnk',
            adminShipmentTemplateParams(
              namaPembeli: userData.username!,
              namaPenjual: cartItems.products!.profiles!.username,
              emailPembeli: userData.email,
              emailAdmin: 'someEmail@gmail.com',
            ),
            const emailJs.Options(
              publicKey: 'somePublicKey',
              privateKey: 'somePrivateKey',
            ),
          );
          print('SUCCESS SEND EMAIL TO ADMIN');
        } catch (e) {
          print(e.toString());
        }
      }
    }`

I got an error that client have been closed in the IF section. Assume that the IF section are meet the criteria to run.

**Comment by geniusvale** [comment] 2023-08-27 13:02
I use flutter 3.7.11, with android for debugging. Here's the code that i run :

![image](https://github.com/emailjs-com/emailjs-flutter/assets/74106164/9e7f54fc-ab8d-41d7-94bf-608384f9e63e)

**Comment by xr0master** [comment] 2023-08-29 05:40
@geniusvale thank you, we will check it on Andriod.
Do you have the same issue in the web mode? (on Chrome)

**Comment by geniusvale** [comment] 2023-08-29 11:22
I don't develop on web and never tried it, so i can't confirm that issues

**Comment by xr0master** [comment] 2023-08-30 16:44
We tested our example on Android and could not reproduce the issue.
Please be sure you are using new versions of SDK and Flutter.

**Comment by cc-bilal** [comment] 2024-01-24 09:20
I still have this issue.
'HTTP request failed. Client is already closed.'
I am using it on web => Chrome.

**Comment by xr0master** [comment] 2024-01-24 10:21
@cc-bilal can you provide a small project where we can see the issue?

**Closed as completed** 2024-06-15 10:22 UTC
